=== lbdroid/cups4j/schema/ippclient/ipp-attribute.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2008 ITS of ETH Zurich, Switzerland, Sarah Windler Burri

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License as published
by the Free Software Foundation; either version 3 of the License,
or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty
of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with this program; if not, see <http://www.gnu.org/licenses/>.
-->
<xs:schema xmlns="http://www.vppserver.ethz.ch/schema/ippclient" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.vppserver.ethz.ch/schema/ippclient" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="attribute-group">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="attribute" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="tag" type="xs:string" use="required"/>
			<xs:attribute name="tag-name" type="xs:string" use="required"/>
			<xs:attribute name="description" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="attribute-list">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="attribute-group" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="description" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="keyword">
		<xs:complexType>
			<xs:attribute name="value" type="xs:string" use="required"/>
			<xs:attribute name="description" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="set-of-keyword">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="keyword" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="description" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="enum">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="value" type="xs:string" use="required"/>
			<xs:attribute name="description" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="set-of-enum">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="enum" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="description" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="attribute-value">
		<xs:complexType>
			<xs:sequence>
				<xs:choice minOccurs="0">
					<xs:element ref="set-of-keyword"/>
					<xs:element ref="set-of-enum"/>
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="tag" type="xs:string" use="required"/>
			<xs:attribute name="tag-name" type="xs:string" use="required"/>
			<xs:attribute name="value" type="xs:string" use="optional"/>
			<xs:attribute name="description" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="attribute">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="attribute-value" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="description" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== lbdroid/cups4j/resources/config/ippclient/ipp-list-of-attributes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2008 ITS of ETH Zurich, Switzerland, Sarah Windler Burri

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License as published
by the Free Software Foundation; either version 3 of the License,
or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty
of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with this program; if not, see <http://www.gnu.org/licenses/>.

List of attributes based on http://www.iana.org/assignments/ipp-registrations
--> 
<attribute-list xmlns="http://www.vppserver.ethz.ch/schema/ippclient" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.vppserver.ethz.ch/schema/ippclient 
					http://www.vppserver.ethz.ch/schema/ippclient/ipp-attribute.xsd">
	<attribute-group tag="0x01" tag-name="operation-attributes-tag" description="operation attributes">
		<attribute name="attributes-charset">
			<attribute-value tag="0x47" tag-name="charset"/>
		</attribute>
		<attribute name="attributes-natural-language">
			<attribute-value tag="0x48" tag-name="naturalLanguage"/>
		</attribute>	
		<attribute name="compression">
			<attribute-value tag="0x44" tag-name="keyword" description="type3 keyword">
				 <set-of-keyword>
					<keyword value="compress"/>
					<keyword value="deflate"/>
					<keyword value="gzip"/>
					<keyword value="none"/>
				 </set-of-keyword>
			</attribute-value>
		</attribute>
		<attribute name="detailed-name">
			<attribute-value tag="0x35" tag-name="textWithLanguage" description="text(MAX)"/>
			<attribute-value tag="0x41" tag-name="textWithoutLanguage" description="text(MAX)"/>
		</attribute>
		<attribute name="document-access-error">
			<attribute-value tag="0x35" tag-name="textWithLanguage" description="text(MAX)"/>
			<attribute-value tag="0x41" tag-name="textWithoutLanguage" description="text(MAX)"/>
		</attribute>
		<attribute name="document-format">
			<attribute-value tag="0x49" tag-name="mimeMediaType"/>
		</attribute> 
		<attribute name="document-name">
			<attribute-value tag="0x36" tag-name="nameWithLanguage" description="name(MAX)"/>
			<attribute-value tag="0x42" tag-name="nameWithoutLanguage" description="name(MAX)"/>
		</attribute>
		<attribute name="document-natural-language">
			<attribute-value tag="0x48" tag-name="naturalLanguage"/>
		</attribute>	
		<attribute name="ipp-attribute-fidelity">
			<attribute-value tag="0x22" tag-name="boolean"/>
		</attribute>
		<attribute name="job-hold-until">
			<attribute-value tag="0x44" tag-name="keyword" description="type3 keyword | name(MAX)">
				<set-of-keyword>
					<keyword value="day-time"/>
					<keyword value="evening"/>
					<keyword value="indefinite"/>
					<keyword value="night"/>
					<keyword value="no-hold"/>
					<keyword value="second-shift"/>
					<keyword value="third-shift"/>
					<keyword value="weekend"/>
				</set-of-keyword>
			</attribute-value>
		</attribute>
		<attribute name="job-id">
			<attribute-value tag="0x21" tag-name="integer" description="integer(1:MAX)"/>
		</attribute>
		<attribute name="job-impressions">
			<attribute-value tag="0x21" tag-name="integer" description="integer(1:MAX)"/>
		</attribute>
		<attribute name="job-k-octets">
			<attribute-value tag="0x21" tag-name="integer" description="integer(0:MAX)"/>
		</attribute>
		<attribute name="job-media-sheets">
			<attribute-value tag="0x21" tag-name="integer" description="integer(0:MAX)"/>
		</attribute>
		<attribute name="job-message-from-operator">
			<attribute-value tag="0x35" tag-name="textWithLanguage" description="text(127)"/>
			<attribute-value tag="0x41" tag-name="textWithoutLanguage" description="text(127)"/>
		</attribute>
		<attribute name="job-name">
			<attribute-value tag="0x36" tag-name="nameWithLanguage" description="name(MAX)"/>
			<attribute-value tag="0x42" tag-name="nameWithoutLanguage" description="name(MAX)"/>
		</attribute>
		<attribute name="job-state">
			<attribute-value tag="0x23" tag-name="enum" description="type1 enum">
				<set-of-enum>
					<enum value="3" name="pending" description="job is waiting to be printed"/>
					<enum value="4" name="pending-held" description="job is held for printing"/>
					<enum value="5" name="processing" description="job is currently printing"/>
					<enum value="6" name="processing-stopped" description="job has been stopped"/>
					<enum value="7" name="canceled" description="job has been canceled"/>
					<enum value="8" name="aborted" description="job has aborted due to error"/>
					<enum value="9" name="completed" description="job has completed successfully"/>
				</set-of-enum>
			</attribute-value>
		</attribute>
		<attribute name="job-state-message">
			<attribute-value tag="0x35" tag-name="textWithLanguage" description="text(MAX)"/>
			<attribute-value tag="0x41" tag-name="textWithoutLanguage" description="text(MAX)"/>
		</attribute>
		<attribute name="job-state-reasons">
			<attribute-value tag="0x44" tag-name="keyword" description="1setOf type2 keyword">
				<set-of-keyword>
					<keyword value="aborted-by-system"/>
					<keyword value="compression-error"/>
					<keyword value="document-access-error"/>
					<keyword value="document-format-error"/>
					<keyword value="job-canceled-at-device"/>
					<keyword value="job-canceled-by-operator"/>
					<keyword value="job-canceled-by-user"/>
					<keyword value="job-completed-successfully"/>
					<keyword value="job-completed-with-errors"/>
					<keyword value="job-completed-with-warnings"/>
					<keyword value="job-data-insufficient"/>
					<keyword value="job-hold-until-specified"/>
					<keyword value="job-incoming"/>
					<keyword value="job-interpreting"/>
					<keyword value="job-outgoing"/>
					<keyword value="job-printing"/>
					<keyword value="job-queued"/>
					<keyword value="job-queued-for-marker"/>
					<keyword value="job-restartable"/>
					<keyword value="job-suspended"/>
					<keyword value="job-transforming"/>
					<keyword value="none"/>
					<keyword value="printer-stopped"/>
					<keyword value="printer-stopped-partly"/>
					<keyword value="processing-to-stop-point"/>
					<keyword value="queued-in-device"/>
					<keyword value="resources-are-not-ready"/>
					<keyword value="service-off-line"/>
					<keyword value="submission-interrupted"/>
					<keyword value="unsupported-compression"/>
					<keyword value="unsupported-document-format"/>
				</set-of-keyword>
			</attribute-value>
		</attribute>
		<attribute name="job-uri">
			<attribute-value tag="0x45" tag-name="uri"/>
		</attribute>
		<attribute name="last-document">
			<attribute-value tag="0x22" tag-name="boolean"/>
		</attribute>
		<attribute name="limit">
			<attribute-value tag="0x21" tag-name="integer" description="integer(1:MAX)"/>
		</attribute>
		<attribute name="message">
			<attribute-value tag="0x35" tag-name="textWithLanguage" description="text(127)"/>
			<attribute-value tag="0x41" tag-name="textWithoutLanguage" description="text(127)"/>
		</attribute>
		<attribute name="my-jobs">
			<attribute-value tag="0x22" tag-name="boolean"/>
		</attribute>
		<attribute name="number-of-intervening-jobs">
			<attribute-value tag="0x21" tag-name="integer" description="integer(0:MAX)"/>
		</attribute>
		<attribute name="original-requesting-user-name">
			<attribute-value tag="0x36" tag-name="nameWithLanguage" description="name(MAX)"/>
			<attribute-value tag="0x42" tag-name="nameWithoutLanguage" description="name(MAX)"/>
		</attribute>
		<attribute name="printer-message-from-operator">
			<attribute-value tag="0x35" tag-name="textWithLanguage" description="text(127)"/>
			<attribute-value tag="0x41" tag-name="textWithoutLanguage" description="text(127)"/>
		</attribute>
		<attribute name="printer-uri">
			<attribute-value tag="0x45" tag-name="uri"/>
		</attribute>
		<attribute name="requested-attributes">
			<attribute-value tag="0x44" tag-name="keyword" description="1setOf keyword"/>
		</attribute>
		<attribute name="requesting-user-name">
			<attribute-value tag="0x36" tag-name="nameWithLanguage" description="name(MAX)"/>
			<attribute-value tag="0x42" tag-name="nameWithoutLanguage" description="name(MAX)"/>
		</attribute>
		<attribute name="status-code">
		<attribute-value tag="0x23" tag-name="enum" description="type2 enum">
				<set-of-enum>
					<enum value="0x0000" name="successful-ok"/>
					<enum value="0x0001" name="successful-ok-ignored-substituted-attributes"/>
					<enum value="0x0002" name="successful-ok-conflicting-attributes"/>
					<enum value="0x0400" name="client-error-bad-request"/>
					<enum value="0x0401" name="client-error-forbidden"/>
					<enum value="0x0402" name="client-error-not-authenticated"/>
					<enum value="0x0403" name="client-error-not-authorized"/>
					<enum value="0x0404" name="client-error-not-possible"/>
					<enum value="0x0405" name="client-error-timeout"/>
					<enum value="0x0406" name="client-error-not-found"/>
					<enum value="0x0407" name="client-error-gone"/>
					<enum value="0x0408" name="client-error-request-entity-too-large"/>
					<enum value="0x0409" name="client-error-request-status-code-too-long"/>
					<enum value="0x040a" name="client-error-document-format-not-supported"/>
					<enum value="0x040b" name="client-error-attributes-or-status-codes-not-supported"/>
					<enum value="0x040c" name="client-error-uri-scheme-not-supported"/>
					<enum value="0x040d" name="client-eror-charset-not-supported"/>
					<enum value="0x040e" name="client-error-conflicting-attribute"/>
					<enum value="0x040f" name="client-error-compession-not-supported"/>
					<enum value="0x0410" name="client-error-compression-error"/>
